### ISSUE TITLE
Accessing k8s cluster from outside with generated certificates doesn't work

### ISSUE THREAD

**Issue by pcm32** [CiscoCloud/kubernetes-ansible#105]
Hi there,

First, thanks for the repo, it has allowed us to advance with kubernetes internally a lot. I have been using this installation, but I cannot manage to access the created cluster with kubectl from an appliance outside of those specifically created by terraform (master or node machines).

I created a kubeconfig file in one of the masters (the main one, which has ip 192.168.0.69 on my openstack installation):

```
CLUSTER_NICK=k8s_test_cluster
SERVER_IP=192.168.0.69
K8S_SSL_PATH=/etc/kubernetes/ssl
CONFIG_PATH=/home/centos/.kube

USER_NICK=kube
username=kube
password=changeme

mkdir -p $CONFIG_PATH
# create kubeconfig entry
kubectl config set-cluster $CLUSTER_NICK \
    --server=https://$SERVER_IP/api \
    --certificate-authority=$K8S_SSL_PATH/ca.crt \
    --embed-certs=true \
    --kubeconfig=$CONFIG_PATH/config
    # Or if tls not needed, replace --certificate-authority and --embed-certs with
    # --insecure-skip-tls-verify=true \

# create user entry
kubectl config set-credentials $USER_NICK \
    --username=$username \
    --password=$password \
    --client-certificate=$K8S_SSL_PATH/kubecfg.crt \
    --client-key=$K8S_SSL_PATH/kubecfg.key \
    --embed-certs=true \
    --kubeconfig=$CONFIG_PATH/config
    # bearer token credentials, generated on kube master
    # --token=$token \
    # use either username|password or token, not both


# create context entry
kubectl config set-context CONTEXT1 --cluster=$CLUSTER_NICK --user=$USER_NICK
```

The keys/certificates are the ones originally created through ansible. I copy the kubeconfig file to the standard location on a machine that is outside the kubernetes cluster (but within the same openstack internal network). This machine is in the same openstack security group as the one created for the k8s masters and nodes.

Checking the config on the external machine, this is loaded correctly:

```
user@ext-vm:~$ ./kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://192.168.0.69/api
  name: k8s_test_cluster
contexts:
- context:
    cluster: k8s_test_cluster
    user: kube
  name: CONTEXT1
current-context: ""
kind: Config
preferences: {}
users:
- name: kube
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: changeme
    username: kube
```

When I try to access through kubectl from this external machine (to set up a proxy to it), however:

```
user@ext-vm:~$ ./kubectl proxy --api-prefix=/custom/
Starting to serve on localhost:8001error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused
```

it doesn't seem to consider the server setting of the config file but instead tries to find a local api-server to connect to.

However, if I explicitly add the --server tag:

```
user@ext-vm:~$ ./kubectl proxy --api-prefix=/custom/ --server=https://192.168.0.69/api
Starting to serve on localhost:8001Please enter Username: kube
Please enter Password: changeme
error: couldn't read version from server: Get https://192.168.0.69/api: x509: certificate is valid for 10.254.0.1, not 192.168.0.69
```

and only this works (ignoring the certificate):

```
user@ext-vm:~$ ./kubectl proxy --api-prefix=/custom/ --server=https://192.168.0.69/api --insecure-skip-tls-verify=true
Starting to serve on localhost:8001Please enter Username: kube
Please enter Password: changeme
```

At this point I can send commands through the REST api on the external machine (ext-vm).

```
user@ext-vm:~$ curl http://localhost:8001/custom/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ]
}
```

What I see from the key/certifcate creation in ansible is that it uses the service ip range, instead of the master's ip on the openstack network to generate the certificates. If I understand correctly, one of the ways of accessing the cluster from outside would be through kubectl dealing with the authentication and opening a proxy from there? or this is not intended in the way that you shaped this k8s installation? Or should I just create a different set of keys that make use of the openstack VM IP for the master that I'm trying to connect to and create a new kubeconfig with those keys/certificates (which I guess I need to give to the api-server)? Or am I using this wrong altogether and I shouldn't aim to have a proxy created outside the cluster? 

Many thanks for any directions!
Pablo

**Comment by ghost** [comment]
Hello Pablo and thank you for your feedback.

I took a look how certificates are generated. The variable `SERVICE_CLUSTER_IP_RANGE` is used to calculate the `service_ip` variable [here](https://github.com/CiscoCloud/mantl-kubernetes/blob/master/roles/kubernetes/files/make-ca-cert.sh#L54). You can verify what IPs/hostnames are used in the certificate this way:

```
openssl x509 -in /etc/kubernetes/ssl/server.crt -text -noout
```

You will see that the masters' hostnames are already used.

It's fine to have the kubectl proxy outside of the cluster as described in the Kubernetes [user guide](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/accessing-the-cluster.md).

**Comment by pcm32** [comment]
Hi Andrii,

Thanks for your answer. I figured out what I needed to make this work. I'll write it here for the record in case anyone else has the same problem. Your suggestion of checking the certificate with openssl gave me the correct hint to sort out things.
- I added the domain name used for the masters to my /etc/hosts (not necessary if you have a DNS setup inside your tenancy) and the then modified the ./kube/config to use that hostname (the one recognized by the certificate) instead of the IP.  
- While kubectl config view sees the config, in my case the field current-context in the ./kube/config was empty, setting this to the only context I had (CONTEXT1) solved the fact that the server and credentials were not being picked up by kubectl <command>.

Setting these, plus what I had in the ./kube/config produced the desired behaviour for kubectl invocations.

**Comment by ghost** [comment]
Thank you for sharing your experience. This repository is sort of upstream for the Kubernetes component in [Mantl](https://github.com/CiscoCloud/microservices-infrastructure) and we will be working to make it more stable and well documented including the security context entries.
