### ISSUE TITLE
dnsmasq only resolved from containers, not from hosts

### ISSUE THREAD

**Issue by moix** [CiscoCloud/kubernetes-ansible#113]
Hi,

I'm trying to understand how the dns resolution works in the hosts of the cluster.

dnsmasq is installed properly in the master, it reads and add the entries in /etc/hosts (addn-hosts=/etc/hosts) and I can resolve them fine from a running container in any of the hosts.

But the resolution doesn't work in the nodes regardless they have the /etc/resolv.conf pointing to ip of the master, any attempt responds with 'unknown host'

**Comment by altvnk** [comment]
Thank you for submitting this issue. Please let me check and try to reproduce behaviour that you are seeing.

**Comment by moix** [comment]
I did some more tests yesterday and turns that is only the ping command what fails, doing nslookup, dig or host works fine. I googled for that and is a common issue (e.g. http://superuser.com/questions/704785/ping-cant-resolve-hostname-but-nslookup-can) but still don't understand why this is happening only in the kubernetes nodes.

**Comment by moix** [comment]
Hi, I managed to find the issue and have just checked that was already fixed in commit f8a986d8e18c67e4f603668c1932a1b5f3d97055

The problem was the mode of /etc/resolv.conf file was previously set with '644' leaving off the leading zero, so the permission of the file were:

```
--w----r-T 1 root root 114 Mar  9 09:11 /etc/resolv.conf
```

with current mode to '0644' works fine :)

Marking as closed, thank you!
