### ISSUE TITLE
Mantl includes kubernetes

### ISSUE THREAD

**Issue by langston-barrett** [CiscoCloud/kubernetes-ansible#116]
See https://github.com/CiscoCloud/mantl/pull/1330 for details.

I think #99 is now somewhat misleading. Can we rename this repo something else? Ping @PeterLamar, @altvnk

**Comment by peterlamar** [comment]
Up to @altvnk, thoughts?

**Comment by altvnk** [comment]
I don't mind, let's rename it back to kubernetes-ansible?

**Comment by peterlamar** [comment]
Makes sense to me

**Comment by altvnk** [comment]
Done
