### ISSUE TITLE
Move to Fedora

### ISSUE THREAD

**Issue by altvnk** [CiscoCloud/kubernetes-ansible#16]
Since all the stuff we are deploying here is pretty bleeding-edge and almost everything is outdated for us in CentOS (like this #7) i propose swap underlying OS to Fedora (e.g. 22).

**Comment by altvnk** [comment]
Then we even don't have to install additional repos and use something like this:

```
yum -y install --enablerepo=updates-testing kubernetes
```

**Comment by kenjones-cisco** [comment]
No objection on what the underlying OS. Too bad the parity between OS distros are still such that it is not just a simple configurable when provisioning the hosts.

I would have to acquire or build a Fedora image for my Openstack environment has there is not one currently available.

**Comment by altvnk** [comment]
Another choice can be Fedora Atomic. Thoughts?

**Comment by kenjones-cisco** [comment]
Considering Atomic is built specifically for use with containers and kubernetes, it should work quite well.

**Comment by peterlamar** [comment]
Both are used by mainstream k8's. Does one of them allow you to use more of their automation?

**Comment by altvnk** [comment]
I suppose we can port some parts from there.

**Comment by altvnk** [comment]
Since all needed components are available in stable CentOS channel this issue can be closed
