### ISSUE TITLE
Help with guestbook example

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/kubernetes-ansible#2]
I have the kubernetes cluster up, just can't seem to make the guestbook example reachable from the outside in the final step. It's likely user error on my part, any advice would be awesome.

**Comment by altvnk** [comment]
Simply uncomment "type:LoadBalancer" in `frontend-service.yaml`, then run `kubectl describe svc frontend` and you will see `NodePort` (31265/TCP) in my case. This port is exposes your service on every single k8s node, so simply point your browser to this port on any node and you will see running guestbook.

```
Name:           frontend
Labels:         name=frontend
Selector:       name=frontend
Type:           LoadBalancer
IP:         10.254.8.13
Port:           <unnamed>   80/TCP
NodePort:       <unnamed>   31265/TCP
Endpoints:      4.0.24.4:80,4.0.40.3:80,4.0.40.4:80
Session Affinity:   None
```

**Comment by kenjones-cisco** [comment]
The message reads:

```
An external load-balanced service was created.  On many platforms (e.g. Google Compute Engine),
you will also need to explicitly open a Firewall rule for the service port(s) (tcp:80,tcp:443) to serve traffic.

See https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/services-firewalls.md for more details.
```

Based on that, we shouldn't have to know the port `31265`. But it does seem that is required to actually see what is running outside of the nodes themselves.

**Comment by altvnk** [comment]
This actually makes sense when you run on Cloud provider like GCE or AWS and have integration with external LB. But for our case it just simpler to know on which port it is published. Here is iptables rules on node:

```
Chain KUBE-NODEPORT-CONTAINER (1 references)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/frontend: */ tcp dpt:31265 redir ports 51351

Chain KUBE-NODEPORT-HOST (1 references)
target     prot opt source               destination
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/frontend: */ tcp dpt:31265 to:172.16.160.50:51351
```

**Comment by kenjones-cisco** [comment]
I found the following items that help especially given external load balancer capabilities:

This provides the discussion and the need I was referring to:
https://github.com/GoogleCloudPlatform/kubernetes/issues/9995

The workaround for now:
https://github.com/GoogleCloudPlatform/kubernetes/tree/v1.0.1/contrib/for-demos/proxy-to-service

**Comment by altvnk** [comment]
Thank you for sharing.
Well, at least for testing current setup is enough, besides that's the real scenario how external traffic passes to services in cloud provider where integration works. Maybe some time ago OpenStack will be in that list )
FYI there is also some interesting project for external connectivity [kiwi](https://github.com/larsks/kiwi)

**Comment by peterlamar** [comment]
Yup, everything works!
