### ISSUE TITLE
Openstack (only) or Cloud Providers in general

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/kubernetes-ansible#21]
The tag line on the repository says "Install and configure Google Kubernetes on OpenStack",
and the README refers to the terraform directory for provisioning an Openstack environment.

But within the terraform directory, there are the samples for AWS and GCE.

Are we planning to support just Openstack, and thus could probably remove the other files from terraform? Or is the plan to support Cloud Providers in general but our focus and primary use case is Openstack?

Probably best to be clear on objectives.

**Comment by altvnk** [comment]
You are right, there is some artefacts that was taken from MI, so we need to cleanup.
In terms of today's standup with @PeterLamar we decided to concentrate on OpenStack and (maybe) bare metal.

**Comment by peterlamar** [comment]
The default k8s project has some great automation to those platforms but was lacking in Openstack. Our baremetal would likely be targeted towards UCS. 

This can likely change if this effort becomes differentiated from k8s but until then I am inclined to either contribute to k8s or place automation here. Open to other ideas as well.

**Comment by kenjones-cisco** [comment]
Answered and clean up done within #30
