### ISSUE TITLE
Ansible issue with Flannel

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/kubernetes-ansible#27]
I believe we resolved this one before. What was the fix again?

TASK: [flannel | configure flannel in etcd] **********************************\* 
failed: [k8s-master] => {"changed": false, "cmd": ["curl", "-L", "http://k8s-master:4001/v2/keys/cluster.local/network/config", "-XPUT", "--data-urlencode", "value@/tmp/flannel.json"], "delta": "0:00:00.235268", "end": "2015-08-02 18:58:00.020974", "rc": 7, "start": "2015-08-02 18:57:59.785706", "warnings": ["Consider using get_url module rather than running curl"]}
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to k8s-master:4001; Connection refused

FATAL: all hosts have already failed -- aborting

**Comment by altvnk** [comment]
Strange, really. Not seen after the last time we fixed it. Do you tried second run?

**Comment by peterlamar** [comment]
If your hostname does not match the inventory, this will happen. We can create a check in the future.
