### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/kubernetes-ansible#45]
As a tenant, my kubernetes cluster has authentication so that people from the internet cannot schedule workloads on my cluster

**Comment by altvnk** [comment]
This is already done, default setup includes: basic auth via user:pass, bearer token auth, client cert auth. All three methods are present in `/etc/kubernetes/kubectl.kubeconfig`. You can download this file and place under `~/.kube/config`. After that you can use `kubectl` from your PC to operate remote k8s cluster over internet, connection is TLS-encrypted, btw.
PS: if you mac-user and using Homebrew, you can install `kubectl` by running `brew install kubernetes-cli`
