### ISSUE TITLE
upgrading environment fails because components not restarted

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/kubernetes-ansible#64]
After the series of updates to etcd and the downstream dependencies within kubernetes components, the interactions with etcd would fail when running the updated ansible roles.

Basically the components were notified to restart but by the time they are used by other components they had not already been restarted and the previous configuration was not compatible.

Look at leveraging `- meta: flush_handlers` at certain points to make sure those handlers are executed prior to those services being consumed.

Because some of the changes are incompatible with existing installations, may need to teardown to clean up the kubernetes installation.

**Comment by altvnk** [comment]
I have the same issue, changes we are made broke my existing cluster. Clean deploy resolved my problem.
