### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by kisoku** [CiscoCloud/kubernetes-ansible#66]
Hi,

I would really like to be able to use this ansible code, but there is no visible license anywhere in the code.
Would it be possible to add a LICENSE file at the top level of the repository to indicate whether this code is open source or not. 

Currently we have to assume this code is closed source, despite it being published on github. 

Thanks

**Comment by altvnk** [comment]
Here you go: #67

**Comment by kisoku** [comment]
Thank you very much

**Comment by altvnk** [comment]
You are welcome! 
Btw, contributions are welcome. Feel free to report any found issues.
