### ISSUE TITLE
ansible error if namespace already exists

### ISSUE THREAD

**Issue by ldejager** [CiscoCloud/kubernetes-ansible#69]
If running ansible for a second time and the kube-system namespace has already been created, the error below is seen. We should expect a check for the namespace before creating it.

``` shell
TASK: [addons | Create kube-system namespace] *********************************
failed: [k8s-master-01] => {"failed": true}
msg: error running kubectl (/bin/kubectl --api-version=v1 create --filename=/etc/kubernetes/manifests/kube-system.yaml) command (rc=1): Error from server: error when creating "/etc/kubernetes/manifests/kube-system.yaml": namespaces "kube-system" already exists
```

**Comment by ldejager** [comment]
assigned to @altvnk as requested

**Comment by kenjones-cisco** [comment]
When it was run the first time, was the environment operational?  Such that it was possible to communicate with the ApiServer to determine status of the different resources?

**Comment by altvnk** [comment]
Closed via 2331169c2976e0832de52b57ee406a7bad7815c2

**Comment by altvnk** [comment]
Yes, apiserver is alive and reports that `namespaces "kube-system" already exists`, the point is `kubectl` does not respond to `kubectl get ns` and reponds to `kubectl get namespace`. Maybe it's beacause we downgraded our installs from `1.1.x` to `1.0.0`.
At least it works for now.

**Comment by ldejager** [comment]
Tested and confirmed it works
