### ISSUE TITLE
Integrate kubernetes-ansible into Mantl

### ISSUE THREAD

**Issue by ghost** [CiscoCloud/kubernetes-ansible#75]
We need to start the integration process as it was earlier discussed. The idea is to integrate Kubernetes into Mantl as an optional component. Users will have a choice to use either Mesos or Kubernetes.

We should freeze work on new features and/or concentrate on those features only that will be required and applicable in the Mantl project. Our goals are stability, clear, high-quality code and a lot of tests.

There are some subtasks that will require concentrated and distinct efforts:
- Make all code consistent with the Mantl code base and write relevant documentation with some examples how to leverage Kubernetes.
- Review all issues in the light of the discussed integration, as some of them may not have sense anymore, or we'd need to rethink them. For example, if we really need Sensu being supplied with Kubernetes or it should go as a separate project/role.
- Calico vs. flannel (current implementation). Calico was merged into Mantl as an optional component. flannel is simpler to set up and already widely tested in this project. If we stay with Calico, update to the latest version might be required (right now we use calico-docker `v0.4.9`, latest version is `v1.1.0`).
- Calico uses etcd and the appropriate role has been already merged. It might be a good idea to reuse that role.
- Extend the Mantl deployment system adding functionality to deploy Kubernetes (the branch `feature/mi-deploy`).

**Comment by peterlamar** [comment]
Makes sense. Which components would be deployed with Mantl K8s?

I don't think it would make sense to standup zookeeper, so perhaps just these?

Consul
Calico
Etcd
K8s

**Comment by ghost** [comment]
Exactly. But I'm not sure about Consul. Looked through https://github.com/CiscoCloud/kubernetes-ansible/issues/55 and still unsure.

**Comment by peterlamar** [comment]
Consul can come later as a separate effort. @ldejager is evaluating it and see if it adds value on k8s.

**Comment by ghost** [comment]
Adding here as a reference: https://github.com/CiscoCloud/microservices-infrastructure/issues/643

**Comment by ghost** [comment]
It's not on our roadmap any more.
