### ISSUE TITLE
Kube ansible plugin

### ISSUE THREAD

**Issue by Smana** [CiscoCloud/kubernetes-ansible#87]
Hello,

I'm working on a  project to build kubernetes on Debian plateforms (with Project Calico network overlay option) there : https://github.com/ansibl8s/setup-kubernetes.

I based my work on your own which is amazing :).
So I'm using the plugin `kube.py` you coded. I wanted to know if you think it could be included into Ansible modules ? 
Indeed we prefer to create a role for each "addon"|"app". What would be the best way to pull your plugin as a dependencie according to you ?

Thanks for your help,
Smana

**Comment by kenjones-cisco** [comment]
Ideally it should be from ansible-extra-modules. It was submitted and even updated based on feedback there. But ultimately not excepted as they have a strong preference for the modules to wrap APIs and not an executable. I've not had the time to go back and update given the short term need we had. As such, it is not part of Ansible.

The easiest way to include would by placing a copy of it within your `library` directory at the root of your project and ansible will automatically pick it up for you.

**Comment by Smana** [comment]
Ok thank you Ken, i'll do that. Great job :)
