### ISSUE TITLE
Rename repo 'mantl-kubernetes'

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/kubernetes-ansible#99]
I propose renaming the repo to Mantl-kubernetes and explaining that this repo is upstream to https://github.com/CiscoCloud/microservices-infrastructure in the readme here. Let me know if this sounds like a crazy idea. @altvnk @stevendborrelli

**Comment by altvnk** [comment]
Done

**Comment by langston-barrett** [comment]
This can probably be closed.

**Comment by altvnk** [comment]
Agreed
